"""Curated seed games library for Productify Gamezone."""

from datetime import datetime, timezone

CURATED_GAMES = [
    {
        "id": "game-cyberpunk-2077",
        "title": "Cyberpunk 2077: Overdrive",
        "slug": "cyberpunk-2077",
        "genre": "Action / RPG",
        "description": "Immerse yourself in Night City with full path tracing and DLSS 3.5 ray reconstruction running on high-end cloud GPUs at 120 FPS.",
        "cover_image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=900&auto=format&fit=crop",
        "banner_image": "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1400&auto=format&fit=crop",
        "hourly_rate_credits": 1.75,
        "min_gpu_vram": "16 GB",
        "recommended_gpu": "NVIDIA RTX 4090 / 3090",
        "docker_image": "productify/game-runner:cyberpunk",
        "storage_required_gb": 70.0,
        "tags": ["ray-tracing", "open-world", "rpg", "aaa"],
        "featured": True,
        "status": "published",
        "plays_count": 142,
        "added_by": "admin",
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "game-doom-eternal",
        "title": "Doom Eternal: Ultra Nightmare",
        "slug": "doom-eternal",
        "genre": "Action / FPS",
        "description": "Hell's armies have invaded Earth. Become the Slayer in an epic campaign to conquer demons across dimensions with lightning-fast input response.",
        "cover_image": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=900&auto=format&fit=crop",
        "banner_image": "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=1400&auto=format&fit=crop",
        "hourly_rate_credits": 1.25,
        "min_gpu_vram": "8 GB",
        "recommended_gpu": "NVIDIA RTX 3070 or better",
        "docker_image": "productify/game-runner:doom",
        "storage_required_gb": 50.0,
        "tags": ["fps", "fast-paced", "demons", "action"],
        "featured": True,
        "status": "published",
        "plays_count": 289,
        "added_by": "admin",
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "game-veloren-rpg",
        "title": "Veloren: Voxel Multiplayer RPG",
        "slug": "veloren",
        "genre": "RPG / Adventure",
        "description": "An open-world, open-source multiplayer voxel RPG inspired by Cube World, Legend of Zelda, and Dwarf Fortress. Explore vast procedurally generated worlds.",
        "cover_image": "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?q=80&w=900&auto=format&fit=crop",
        "banner_image": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1400&auto=format&fit=crop",
        "hourly_rate_credits": 0.65,
        "min_gpu_vram": "6 GB",
        "recommended_gpu": "NVIDIA RTX 3060",
        "docker_image": "productify/game-runner:veloren",
        "storage_required_gb": 15.0,
        "tags": ["voxel", "open-source", "rpg", "multiplayer"],
        "featured": False,
        "status": "published",
        "plays_count": 94,
        "added_by": "admin",
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "game-supertuxkart-4k",
        "title": "SuperTuxKart Nitro 4K",
        "slug": "supertuxkart-4k",
        "genre": "Racing / Arcade",
        "description": "3D open-source arcade kart racer featuring varied tracks, battle modes, and split-screen multiplayer streaming directly to your web browser.",
        "cover_image": "https://images.unsplash.com/photo-1511882150382-421056c89033?q=80&w=900&auto=format&fit=crop",
        "banner_image": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1400&auto=format&fit=crop",
        "hourly_rate_credits": 0.45,
        "min_gpu_vram": "4 GB",
        "recommended_gpu": "Any GPU with 4GB VRAM",
        "docker_image": "productify/game-runner:supertuxkart",
        "storage_required_gb": 8.0,
        "tags": ["racing", "arcade", "kart", "multiplayer"],
        "featured": False,
        "status": "published",
        "plays_count": 182,
        "added_by": "admin",
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "game-cs2-arenas",
        "title": "Counter-Strike 2: Low-Latency Arenas",
        "slug": "cs2-arenas",
        "genre": "Competitive FPS",
        "description": "Sub-tick competitive tactical shooter streaming at 240Hz refresh rates from enterprise GPU nodes located in low-latency metro data centers.",
        "cover_image": "https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=900&auto=format&fit=crop",
        "banner_image": "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1400&auto=format&fit=crop",
        "hourly_rate_credits": 1.10,
        "min_gpu_vram": "8 GB",
        "recommended_gpu": "NVIDIA RTX 3070 or better",
        "docker_image": "productify/game-runner:cs2",
        "storage_required_gb": 45.0,
        "tags": ["competitive", "esports", "fps", "valve"],
        "featured": True,
        "status": "published",
        "plays_count": 315,
        "added_by": "admin",
        "created_at": datetime.now(timezone.utc).isoformat(),
    },
    {
        "id": "game-flight-sim-x",
        "title": "Flight Simulator: Global Aviator",
        "slug": "flight-sim-x",
        "genre": "Simulation",
        "description": "Test your piloting skills against real-time atmospheric conditions, photorealistic terrain, and high-fidelity cockpits from light aircraft to wide-body jets.",
        "cover_image": "https://images.unsplash.com/photo-1519074069444-1ba4eae16e60?q=80&w=900&auto=format&fit=crop",
        "banner_image": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=1400&auto=format&fit=crop",
        "hourly_rate_credits": 1.60,
        "min_gpu_vram": "12 GB",
        "recommended_gpu": "NVIDIA RTX 4080 / 3080",
        "docker_image": "productify/game-runner:flight-sim",
        "storage_required_gb": 80.0,
        "tags": ["simulation", "aviation", "photorealistic", "planes"],
        "featured": True,
        "status": "published",
        "plays_count": 120,
        "added_by": "admin",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
]
